# Generated by Django 5.2.7 on 2026-06-29 16:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0153_release_2_12_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
